### ISSUE TITLE
Consider adding more info to the README.md table

### ISSUE THREAD

**Issue by rossjones** [redecentralize/alternative-internet#142]
There's quite a lot of data pulled from Ohloh, and we should possibly display it in the table.

**Comment by millette** [comment]
Never too late ;-)

**Comment by rossjones** [comment]
We abandoned the ohloh integration after it changed name and the API stopped working reliably.  Not sure the generated pages were actually that readable, so we switched back to plain and simple README a couple of months back.

**Comment by millette** [comment]
I just found it funny a see an issue closed after 4-5 years, but I understand.

Cheers!

**Comment by rossjones** [comment]
Just tidying up ;)
