### ISSUE TITLE
Add ZeroNet

### ISSUE THREAD

**Issue by christopherturner** [redecentralize/alternative-internet#214]
I believe ZeroNet certainly qualifies for this list.

*Official site:* http://zeronet.io/

*Github Repo:* https://github.com/HelloZeroNet/ZeroNet

**Comment by bumi** [comment]
related: #212 
and +1 for zeronet!

**Comment by wigy-opensource-developer** [comment]
#212 is more complete than this pull request. I suggest this issue to be closed and #212 to be merged.
