### ISSUE TITLE
Way to much outdated info here..

### ISSUE THREAD

**Issue by GnstheGrain** [redecentralize/alternative-internet#222]
ie. 
- Thali Project should point to their github VSC, not their old Codeplex one..
- Red Matrix is now Hubzilla 
- etc...

Just reporting..

**Comment by Enamex** [comment]
If you could help with checking all the listed projects and compiling a list of the out-of-date ones I could make a pull request with the updated data.

**Comment by GnstheGrain** [comment]
@Enamex if time allow me to, I will definitely.

**Comment by rossjones** [comment]
Started moving some to the *-dead sections but the ones mentioned are fixed.
