### ISSUE TITLE
Distributed - Decentral

### ISSUE THREAD

**Issue by ShalokShalom** [redecentralize/alternative-internet#227]
There is a difference between these two, which get ignored by this list - IPFS is, as an example distributed. 

I am to stupid/lazy to push a pull request, Zero Net, Ring and MORPHiS are other distributed systems.

**Comment by rossjones** [comment]
Pota-to, po-tato. It's not a hard and fast rule.

I'm too lazy to add them for you, I'm sure somebody will come add a PR at some point.

**Comment by ShalokShalom** [comment]
It confuses potential customers
