### ISSUE TITLE
Avatar and Cowbox are down

### ISSUE THREAD

**Issue by lcpz** [redecentralize/alternative-internet#231]
I didn't check other links, so more projects (at least the sites here reported) might be down too.

**Comment by jnv** [comment]
[Avatar's latest tweet](https://twitter.com/avatar_ai):

> Rumors of my death have been greatly exaggerated...

Well, the domain is for purchase.

As for CoWBox, there seem to be other resources: [Tumblr](http://cowboxisen.tumblr.com/) and [Twitter](https://twitter.com/cowbox_isen), though with last activity in April 2014, I suppose the project is pretty much dead.

**Comment by rossjones** [comment]
Avatar's latest tweet is gone so presumably it is no more. Have moved them both to an 'Apparently Dead' category.
