### ISSUE TITLE
Matrix is not JavaScript

### ISSUE THREAD

**Issue by Matrixcoffee** [redecentralize/alternative-internet#234]
Matrix is an open standard, not any of its server or client implementations, so language should probably be n/a. If you want to track lines.of ``code`` and such, the repository to watch is https://github.com/matrix-org/matrix-doc , although it contains lots of other things besides the Matrix spec.

**Comment by rossjones** [comment]
We've gone back to the simple readme now.  Although we lost a little bit of info (activity for instance) it's a lot clearer and easier to read.
