### ISSUE TITLE
Improve layout

### ISSUE THREAD

**Issue by tukkek** [redecentralize/alternative-internet#239]
The current layout isn't very good to read: the descriptions can get very long but they're competing for space with other 5 columns that are just empty most of the time. It looks bad and requires constant scrolling down even on big computer screens.

It should be easy to fix. My suggestion would be to have only 2 columns:  description and details. Compare the readability of each method:

---------

**Current layout**

 Name | Description | [Main Language](README_LANG.md) | [Commits](README_COMMITS.md) | [LOC](README_LOC.md) | [Total Contributors](README_CONTRIB.md) | [Age](README_AGE.md) |
| ---- | ----------- | ----------- | ------: | --: | --: | --: |
|Cozy|[Cozy](http://cozy.io) is a personal cloud you can host, hack and delete. With Cozy, you manage your web apps like you were on your smartphone. It provides an open market place from where you can install the web app you made yourself (Cozy is a [personal PaaS](http://cozy.io/hack/getting-started/architecture-overview.html)). Today, the most successful applications are Contact and Calendar managers that you can synchronize with any device. Check the [demo](https://demo.cozycloud.cc) to discover more applications.|CoffeeScript|854 |8 K|13 |3 year(s)|

------------

**Proposed layout**

| Project | Details | 
| - | --- |
|[Cozy](http://cozy.io) is a personal cloud you can host, hack and delete. With Cozy, you manage your web apps like you were on your smartphone. It provides an open market place from where you can install the web app you made yourself (Cozy is a [personal PaaS](http://cozy.io/hack/getting-started/architecture-overview.html)). Today, the most successful applications are Contact and Calendar managers that you can synchronize with any device. Check the [demo](https://demo.cozycloud.cc) to discover more applications.|[Language](README_LANG.md): CoffeeScript<br/>[Commits](README_COMMITS.md): 854<br/>[LOC](README_LOC.md): 8K<br/>[Contributors](README_CONTRIB.md): 13<br/>[Age](README_AGE.md): 3 year(s)|

-----

The first "name" column is redundant because the name and link are always the first thing to appear in each project's description as well. Having the headers "repeated" on each line of the table (on the second column) is also much more useful because when you're halfway across the list you can't even scroll up easily to remind yourself what each number means. 

The overall readability, which is my biggest concern, is also greatly improved as can be seen on the example above - especially on smaller screens (such as mobile phones).

**Comment by ozra** [comment]
Wow, this was _exactly_ the issue and suggestion I was gonna write. Two thumbs up on this suggestion :)

**Comment by rossjones** [comment]
We 'fixed' this by going back to the original style of readme which is clearer, easier to manage, easier to send PRs for.
