### ISSUE TITLE
d.tube is a good entry point for people new to decent sys

### ISSUE THREAD

**Issue by ozra** [redecentralize/alternative-internet#244]
Spreading the concept of decentralization to more people is, kind of, the root of decentralization. D.tube, despite having a centrally stored web-interface to the system, but anyone could start their own webinterface, os a good starting point for most people of today I'd guess

**Comment by rossjones** [comment]
If you could provide a one paragraph description of what it is, we can get it added to the list....

**Comment by RadRussianRus** [comment]
"D.Tube is the first crypto-decentralized video platform, built on top of the STEEM Blockchain and the IPFS peer-to-peer network."
Source: https://about.d.tube/

**Comment by ozra** [comment]
Sorry, didn't see this until now. Great to see the addition! Stay decent! :-)
