### ISSUE TITLE
Addition to README.md requested

### ISSUE THREAD

**Issue by sbadakhc** [redecentralize/alternative-internet#265]
Hi,

Can you include an link to the Cordite Foundation in the README.md?

http://docs.cordite.foundation/en/latest/

Cordite provides de-centralised governance and economic services to mutually distrusting corporations wishing to solve distributed challenges in their industries.

Thanks,
Sal.

**Comment by rossjones** [comment]
So I think Corda.net, yes (with a link to cordite at the end) but I'm _trying_ to keep this focused on tech rather than governance models.
