### ISSUE TITLE
Add Solid project to general

### ISSUE THREAD

**Issue by alexcorvis84** [redecentralize/alternative-internet#288]
I think the Solid project should be listed in this great list (under general i.e)

https://solidproject.org/ (New 'Official' Web)
https://inrupt.com/solid
https://solid.mit.edu/

Solid is a project lead by Tim Berners Lee that aims to re-decentralized the web. 
Solid (derived from "social linked data") is a proposed set of conventions and tools for building decentralized Web applications based on Linked Data principles.
Solid is modular and extensible. It relies as much as possible on existing W3C standards and protocols.

**Comment by rossjones** [comment]
Cool, would you have time for a PR?

**Comment by alexcorvis84** [comment]
Sure! Just requested PR! ✅

**Comment by rossjones** [comment]
Much appreciated and merged ;)
