### ISSUE TITLE
Possibly dead projects

### ISSUE THREAD

**Issue by bubonicfred** [redecentralize/alternative-internet#321]
This is by no means definitive (did not check everything)
KA lite  is no longer under active development, superceded by Kolibri 
eplug redirects to https://www.tokens.net/de/kryptow%C3%A4hrung/bitcoin-btc/ (which is shutting down)
The following don't load:
unsystem
lorea
weborganizm
ostel
Also I don't know how pushing to the github.io site works, but that needs markings for dead projects

**Comment by milahu** [comment]
[avatar.ai](https://avatar.ai/) domain is for sale

[iop.global](https://iop.global/) has a redirect to hydraledger.io

[gittorrent.org](http://gittorrent.org/) is gone
