### ISSUE TITLE
Broken URLs / spam websites

### ISSUE THREAD

**Issue by xplosionmind** [redecentralize/alternative-internet#327]
By visiting:
- <https://amplify.net>
- <https://avatar.ai>
- <https://bip.io>
- <https://dappstore.dappcentral.com/>
- <https://deadc.net/>
- <https://www.dendr.io/>

…listed in this repository, either the page does not exist or you are redirected to a spam page.

**Comment by rossjones** [comment]
Thanks, have moved those not already in 'totally dead' to that section.
