### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by Emmastro** [redecentralize/alternative-internet#353]
The links below aren't working:

- http://0bin.net/
- http://yaap.it/

**Comment by rossjones** [comment]
Fixed up now (moved to Dead) - thanks @Emmastro

**Comment by Emmastro** [comment]
Good day,
I hope you're well.

Please, request for review from someone currently in the program. I am an alumni, graduated from the first cohort. I don't have permission to give you a review.
I am currently writing a technical blog post you might be interested in reading, from Medium: ***@***.***

***@***.***>
Emmanuel Murairi – ***@***.***>
Read writing from Emmanuel Murairi on Medium. I am a software engineer and violinist. I write about tech, experience and topics of interest. Every day, Emmanuel Murairi and thousands of other voices read, write, and share important stories on Medium.
medium.com


You'll see stories from a time when a client's website got hacked <https://blog.devgenius.io/my-client-website-got-hacked-lessons-learned-and-steps-to-strengthen-website-security-a37fda9e1080> to my personal experience as a young professional in tech<https://blog.startupstash.com/navigating-your-professional-journey-in-tech-lessons-from-a-young-professional-2c7c1f921a6a>.
[https://miro.medium.com/v2/resize:fit:1200/1*XkYFRTBzPisQ5qmyg67r7Q.jpeg]<https://blog.startupstash.com/navigating-your-professional-journey-in-tech-lessons-from-a-young-professional-2c7c1f921a6a>
Navigating Your Professional Journey in Tech: Lessons From a Young Professional<https://blog.startupstash.com/navigating-your-professional-journey-in-tech-lessons-from-a-young-professional-2c7c1f921a6a>
Are you a young professional? Do you remember the career advice that encourages us to say “yes” to any work that comes our way? The one…
blog.startupstash.com


[https://miro.medium.com/v2/resize:fit:1200/1*RiF5y56v23CveOIQ0WQNeA.png]<https://blog.devgenius.io/my-client-website-got-hacked-lessons-learned-and-steps-to-strengthen-website-security-a37fda9e1080>
My Client Website Got Hacked: Lessons Learned and Steps to Strengthen Website Security<https://blog.devgenius.io/my-client-website-got-hacked-lessons-learned-and-steps-to-strengthen-website-security-a37fda9e1080>
During the first week of January, flying back to Mauritius, I get an intriguing message from my colleague saying one of our client websites…
blog.devgenius.io


Let me know if you have any thoughts on them, and feel free to follow me for my next articles.




_____________________________________

Emmanuel Murairi

African Leadership Academy | Class of 2018
Website: http://emmamurairi.me<http://emmamurairi.me/>
________________________________
