### ISSUE TITLE
nostr

### ISSUE THREAD

**Issue by telamon** [redecentralize/alternative-internet#354]
I kinda feel nostr.net belongs on this list.
They're not decentralized in any traditional sense but at the moment it's a lot more decentralized than anything related to etherium per say.

Essentially nostr is a kind of coinless DAG Blockchain were all miner nodes try to run JSON.parse() as fast as they can, kinda healthier than proof of work -
recursively insane but fun.

Cheers!

**Comment by rossjones** [comment]
Good call on the protocol.  The blockchain/mining seems quite tangential to the actual protocol so I've ignored that aspect :D
